#!/usr/bin/env python3
"""Regenerate the shared Inter + Bravura MTSDF atlas.

Requires msdf-atlas-gen 1.4. The checked-in output is consumed directly by
Dawn/WebGPU and Metal, so application builds do not depend on this tool.
"""

from __future__ import annotations

import json
import pathlib
import shutil
import subprocess
import tempfile


ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "src" / "render" / "assets"
ZIG_OUTPUT = ROOT / "src" / "render" / "glyph_atlas.zig"
INTER = ROOT / "vendor" / "fonts" / "InterVariable.ttf"
BRAVURA = ROOT / "vendor" / "fonts" / "Bravura.otf"


def zig_float(value: float) -> str:
    rendered = f"{value:.9g}"
    return rendered if "." in rendered or "e" in rendered else rendered + ".0"


def main() -> None:
    generator = shutil.which("msdf-atlas-gen")
    if generator is None:
        raise SystemExit("msdf-atlas-gen 1.4 is required (brew install msdf-atlas-gen)")
    if not INTER.exists() or not BRAVURA.exists():
        raise SystemExit("vendored Inter and Bravura font files are missing")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="score-atlas-") as temp:
        temporary = pathlib.Path(temp)
        image = temporary / "glyph-atlas.rgba"
        metadata = temporary / "glyph-atlas.json"
        subprocess.run(
            [
                generator,
                "-varfont",
                f"{INTER}?wght=450&opsz=14",
                "-chars",
                "[0x20, 0x7e], [0xa0, 0xff]",
                "-fontname",
                "Inter",
                "-and",
                "-font",
                str(BRAVURA),
                "-chars",
                "0xe050, 0xe062, [0xe080, 0xe089], 0xe0a2, 0xe0a3, 0xe0a4, 0xe240, 0xe241",
                "-fontname",
                "Bravura",
                "-type",
                "mtsdf",
                "-format",
                "rgba",
                "-imageout",
                str(image),
                "-json",
                str(metadata),
                "-size",
                "64",
                "-pxrange",
                "8",
                "-potr",
                "-yorigin",
                "top",
            ],
            check=True,
        )
        data = json.loads(metadata.read_text())
        raw_image = image.read_bytes()
        expected_size = data["atlas"]["width"] * data["atlas"]["height"] * 4
        if raw_image.startswith(b"RGBA") and len(raw_image) == expected_size + 12:
            raw_image = raw_image[12:]
        if len(raw_image) != expected_size:
            raise SystemExit(f"unexpected atlas byte count: {len(raw_image)} (expected {expected_size})")
        (OUTPUT_DIR / "glyph-atlas.rgba").write_bytes(raw_image)

    atlas = data["atlas"]
    variants = {variant["name"]: variant for variant in data["variants"]}
    lines = [
        "// Generated by scripts/generate-glyph-atlas.py; do not hand-edit.",
        "",
        "pub const Glyph = struct {",
        "    codepoint: u21,",
        "    advance: f32,",
        "    plane: [4]f32, // left, top, right, bottom in ems",
        "    uv: [4]f32, // left, top, right, bottom normalized",
        "};",
        "",
        f"pub const width: u32 = {atlas['width']};",
        f"pub const height: u32 = {atlas['height']};",
        f"pub const pixel_range: f32 = {zig_float(atlas['distanceRange'])};",
        'pub const pixels = @embedFile("assets/glyph-atlas.rgba");',
        "",
    ]
    for zig_name, variant_name in (("ui_glyphs", "Inter"), ("music_glyphs", "Bravura")):
        lines.append(f"pub const {zig_name} = [_]Glyph{{")
        for glyph in variant_name and variants[variant_name]["glyphs"]:
            codepoint = glyph["unicode"]
            advance = zig_float(glyph["advance"])
            plane = glyph.get("planeBounds", {"left": 0, "top": 0, "right": 0, "bottom": 0})
            bounds = glyph.get("atlasBounds", {"left": 0, "top": 0, "right": 0, "bottom": 0})
            p = ", ".join(zig_float(plane[key]) for key in ("left", "top", "right", "bottom"))
            u = ", ".join(
                zig_float(bounds[key] / atlas["width" if key in ("left", "right") else "height"])
                for key in ("left", "top", "right", "bottom")
            )
            lines.append(
                f"    .{{ .codepoint = 0x{codepoint:x}, .advance = {advance}, .plane = .{{ {p} }}, .uv = .{{ {u} }} }},"
            )
        lines.extend(("};", ""))
    lines.extend(
        (
            "pub fn findUi(codepoint: u21) ?Glyph {",
            "    return find(&ui_glyphs, codepoint);",
            "}",
            "",
            "pub fn findMusic(codepoint: u21) ?Glyph {",
            "    return find(&music_glyphs, codepoint);",
            "}",
            "",
            "fn find(glyphs: []const Glyph, codepoint: u21) ?Glyph {",
            "    var low: usize = 0;",
            "    var high: usize = glyphs.len;",
            "    while (low < high) {",
            "        const middle = low + (high - low) / 2;",
            "        if (glyphs[middle].codepoint < codepoint) low = middle + 1 else high = middle;",
            "    }",
            "    if (low < glyphs.len and glyphs[low].codepoint == codepoint) return glyphs[low];",
            "    return null;",
            "}",
            "",
            'test "atlas byte count and lookups are consistent" {',
            '    const testing = @import("std").testing;',
            "    try testing.expectEqual(@as(usize, width * height * 4), pixels.len);",
            "    try testing.expect(findUi('A') != null);",
            "    try testing.expect(findMusic(0xe050) != null);",
            "}",
            "",
        )
    )
    ZIG_OUTPUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
